### ISSUE TITLE
Should not silently use sync function

### ISSUE THREAD

**Issue by julien-f** [sindresorhus/user-info#1]
IMHO, after modules initialization, blocking the event loop should not happen without the explicit knowledge of the developer, I think it would be better if you move the code outside of the function call.

**Comment by sindresorhus** [comment]
But this is a polyfill of the native API which does exactly that.

**Comment by julien-f** [comment]
Even though it looks weird to me I believe Node people know what's the right thing to do better than me.

Thanks for your answer.
